name: auto-approve-and-merge

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

permissions:
  pull-requests: write
  contents: write

jobs:
  approve-and-merge-by-dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Approve a PR
        run: gh pr review --approve "$PR_URL"
      - name: Enable auto-merge for Dependabot PRs
        if: |
          (steps.metadata.outputs.update-type == 'version-update:semver-patch' ||
          steps.metadata.outputs.update-type == 'version-update:semver-minor') &&
          !contains(steps.dependabot-metadata.outputs.dependency-names, 'vite') &&
          !contains(steps.dependabot-metadata.outputs.dependency-names, 'react-router') &&
          !contains(steps.dependabot-metadata.outputs.dependency-names, 'antd') && 
          !contains(steps.dependabot-metadata.outputs.dependency-names, 'prettier')
        run: gh pr merge --auto --squash "$PR_URL"
    env:
      PR_URL: ${{github.event.pull_request.html_url}}
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
